Open NFT1 CHIP
Chia-Network/chips pull request #19
Opened 2022-06-06 21:19 UTC by danieljperry

2022-06-08 02:43 UTC, BrandtH22 reviewed
Overall, the CHIP is looking great and I am excited for NFT1!

2022-06-08 02:43 UTC, BrandtH22 commented on CHIPs/chip-dan-perry-nft1.md
> +  * Upon minting an NFT, a SHA-256 hash of the file being linked to shall be embedded within the NFT itself. This gives a permanent way to verify the NFT's contents, even if each of the links is brok
Do we need to define that the hash is added separately to allow for delayed reveals? 
ex. provide the correct file hash but a URL that links to a dummy image until the NFT is revealed

2022-06-08 02:43 UTC, BrandtH22 commented on CHIPs/chip-dan-perry-nft1.md
> +* NFT1 NFTs must be image files. The only supported types are jpg, gif, png and svg
We should not limit the file types. I propose changing must to should here.

2022-06-08 02:43 UTC, BrandtH22 commented on CHIPs/chip-dan-perry-nft1.md
> +  * Upon the NFT's minting, the content of the first item in this list must hash to the Data Hash (defined below)
I propose changing this must to a should.
See above comment regarding delayed reveals.

2022-06-08 02:43 UTC, BrandtH22 commented on CHIPs/chip-dan-perry-nft1.md
> +  * Upon the NFT's minting and sale, the content of the first item in this list must hash to the Metadata Hash (defined below)
I propose changing this must to a should.
See above comment regarding delayed reveals.

2022-06-08 02:43 UTC, BrandtH22 commented on CHIPs/chip-dan-perry-nft1.md
> +      {
Can we add a version field as proposed here:
https://developers.chia.net/t/nft-metadata-file-schema/433/15

2022-06-08 02:43 UTC, BrandtH22 commented on CHIPs/chip-dan-perry-nft1.md
> +  * **License URI list:** A list of URIs that map to the NFT's licensing and legal requirements
Will there be recommended licenses upon NFT1 launch?

2022-06-08 02:43 UTC, BrandtH22 commented on CHIPs/chip-dan-perry-nft1.md
> +The NFT1 standard includes Offer 2.0, which builds on top of the [Offer 1.0 standard](https://chialisp.com/docs/puzzles/offers) to enable the buying, selling and trading of XCH, CATs and NFTs.
Will offer2 have its own CHIP?

2022-06-08 02:43 UTC, BrandtH22 commented on CHIPs/chip-dan-perry-nft1.md
> +### RPC Calls
These all appear to be the wallet RPC commands, will there be additional Full Node RPC commands for NFT1?

2022-06-08 02:57 UTC, BrandtH22 commented on CHIPs/chip-dan-perry-nft1.md
> +  * **Metadata Hash:** A SHA-256 hash of the contents of the first item of the Metadata URI list. The Owner may modify this hash
If the owner can modify the metadata hash could they change the attributes that ascribe rarity of an NFT?

2022-07-01 18:55 UTC, CommanderMoto commented
So, since this CHIP is in the wild as of v1.4.0 ... isn't it time we merge this PR for real?

2022-07-01 19:00 UTC, danieljperry commented
> So, since this CHIP is in the wild as of v1.4.0 ... isn't it time we merge this PR for real?

The CHIP is the NFT1 standard. Chia version 1.4 is a separate thing. It implements most of this standard, but not quite all of it yet. Soon we'll go through the formal review process and make any last-minute changes before finalizing the standard. Once it's final it can't change, so we want to make sure we get it right.

2022-08-03 01:05 UTC, danieljperry commented on CHIPs/chip-dan-perry-nft1.md
> +  * Upon minting an NFT, a SHA-256 hash of the file being linked to shall be embedded within the NFT itself. This gives a permanent way to verify the NFT's contents, even if each of the links is brok
Agreed and updated.

2022-08-03 01:06 UTC, danieljperry commented on CHIPs/chip-dan-perry-nft1.md
> +* NFT1 NFTs must be image files. The only supported types are jpg, gif, png and svg
Updated to allow any media format.

2022-08-03 01:07 UTC, danieljperry commented on CHIPs/chip-dan-perry-nft1.md
> +  * Upon the NFT's minting, the content of the first item in this list must hash to the Data Hash (defined below)
updated

2022-08-03 01:09 UTC, danieljperry commented on CHIPs/chip-dan-perry-nft1.md
> +      {
The metadata contents have been moved outside of this CHIP. See CHIP7 for more info.

2022-08-03 01:12 UTC, danieljperry commented on CHIPs/chip-dan-perry-nft1.md
> +  * **Metadata Hash:** A SHA-256 hash of the contents of the first item of the Metadata URI list. The Owner may modify this hash
This has been updated to "This hash shall not be modified after the NFT's minting".

2022-08-03 01:14 UTC, danieljperry commented on CHIPs/chip-dan-perry-nft1.md
> +### RPC Calls
There aren't any specific full node RPCs in the current NFT standard.

2022-08-10 18:00 UTC, ddesiderio commented on CHIPs/chip-0005.md
> +* **Minter's DID:** If a DID was used in this NFT's minting, then the Minter’s DID shall be discoverable by blockchain explorers
Can you add more info on how this linking between NFT<->DID is done and can be verified? For example, if there's a stamp of a DID signature required to be added after each NFT transfer/mint how will that look and how can it be verified? Some examples may help for this too, to ensure that community tools snap to the same way of displaying/verifying provenance

2022-08-11 01:07 UTC, danieljperry commented on CHIPs/chip-0005.md
> +* **Minter's DID:** If a DID was used in this NFT's minting, then the Minter’s DID shall be discoverable by blockchain explorers
This requirement has been removed.

2022-08-19 21:04 UTC, wriches commented on CHIPs/chip-0005.md
> +  * There will be multiple off-chain metadata formats, each of which will have its own Process CHIP. These CHIPs shall specify a list of required, recommended, and/or optional fields. If a formalised
JSON should be recommended but not mandatory for off-chain metadata formats, in order to maximise interoperability and reduce the logic required to process multiple formats.

2022-08-19 21:12 UTC, wriches requested changes

2022-08-19 21:12 UTC, wriches commented on CHIPs/chip-0005.md
> +  * There will be multiple off-chain metadata formats, each of which will have its own Process CHIP. These CHIPs shall specify a list of required, recommended, and/or optional fields. If a formalised
Charset requirements should be provided here. Something like "Off-chain metadata formats should be encoded in UTF-8 without BOM".

2022-08-19 21:12 UTC, wriches commented on CHIPs/chip-0005.md
> +  * There will be multiple off-chain metadata formats, each of which will have its own Process CHIP. These CHIPs shall specify a list of required, recommended, and/or optional fields. If a formalised
JSON should be recommended but not mandatory for off-chain metadata formats, in order to maximise interoperability and reduce the logic required to process multiple formats.

2022-09-30 15:21 UTC, wriches approved these changes

2022-09-30 15:22 UTC, merged